@startuml
' NOTE: option + D でpreview
!include tables.pu
ワークスペース }o-d-o{ ワークスペース_ユーザー
ユーザー }o-d-o{ ワークスペース_ユーザー
ユーザー }o-d-o{ ユーザー_チャンネル
チャンネル }o-d-o{ ユーザー_チャンネル
ユーザー ||-d-o{ メッセージ
チャンネル ||-d-o{ メッセージ
@enduml
