@startuml

entity ワークスペース {
   ID
   ワークスペース名
}

entity ワークスペース_ユーザー {
   ワークスペースID
   ユーザーID
}

entity ユーザー {
   ID
   姓
   名
}

entity チャンネル {
   ID
   チャンネル名
}

entity ユーザー_チャンネル {
   ユーザーID
   チャンネルID
}

entity メッセージ {
   ID
   内容
   親メッセージID
   チャンネルID
   ユーザーID
   登録日時
}

@enduml
