@startuml


entity orders {
   (PK)id
   last_name
   first_name
   phone
   is_paid
   is_takeout
   memo
   created_at
   created_by
   updated_at
   updated_by
}

entity order_items {
   (PK)id
   (FK)order_id
   (FK)item_id
   quantity
   is_with_wasabi
}

entity items {
   (PK)id
   name
   price
   (FK)category_id
   created_at
   created_by
   updated_at
   updated_by
}

entity category {
   (PK)id
   name
}

@enduml
