@startuml
' NOTE: option + D でpreview
!include tables.pu
ワークスペース ||-d-o{ ワークスペース_ユーザー
ワークスペース ||-d-o{ チャンネル
ユーザー ||-d-o{ ワークスペース_ユーザー
ユーザー ||-d-o{ チャンネル_ユーザー
チャンネル ||-d-o{ チャンネル_ユーザー
ユーザー ||-d-o{ メッセージ
チャンネル ||-d-o{ メッセージ
@enduml
